### ISSUE TITLE
Find a source of the connectivity issues

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/waterfall#38] opened 2022-11-10 15:12 UTC
- Some users can't see other users during the call.
- Connections being interrupted during the call without an obvious reason.

**Comment by daniel-abramov** [comment] 2022-12-06 11:13
**UPD:** So far we have not been able to identify misbehavior in the server (at least not in the refactored version), but we've noticed a weird behavior of a client when the client split-brains bypassing the SFU communication and connecting P2P in certain cases. It's not yet clear why and it seems like there has been an attempt to fix it. We need to retest it to see if the issue is gone.

**Comment by SimonBrandner** [comment] 2022-12-15 15:40
Is this issue still relevant?

**Comment by daniel-abramov** [comment] 2022-12-15 15:42
No, I think we can close it!

**Closed** 2022-12-15 15:42 UTC
Labels: T-Defect
